### ISSUE TITLE
Terraformers Mod Compat

### ISSUE THREAD

**Issue by Vaerian** [RandomMcSomethin/fallingleaves#1]
Hey we'd love to see support for the leaves in Terrestria and Traverse. That would be cool when you get around to it.

**Comment by MopsTMC** [comment]
They work for me! Not sure though if there's support for every type of leaf
![2020-11-16_21 05 36](https://user-images.githubusercontent.com/74558936/99296556-9f980680-284f-11eb-84c9-7c33211046a2.png)

**Comment by Fourmisain** [comment]
As long as the mod makers extend from the `LeavesBlock` class, falling leaves will spawn from them.
Terrestria and Traverse should both be completely compatible.

Note however, that in 1.4 there are some leaf blocks that are disabled by default.
For example
```
terrestria:redwood_leaves
terrestria:hemlock_leaves
terrestria:cypress_leaves
traverse:fir_leaves
```
are considered conifers and the conifer leaf spawn rate is 0 by default.
There are also
```
terrestria:yucca_palm_leaves
terrestria:jungle_palm_leaves
```
which are considered large leafed, so they don't drop falling leaves.

1.5 will make configuring leaves much easier, there are still some hurdles to be crossed however.

If you find a block that doesn't work, let us know, for now I'll close this issue.
