### ISSUE TITLE
Crash report: Could not execute entrypoint stage 'client'

### ISSUE THREAD

**Issue by SepiaPages** [RandomMcSomethin/fallingleaves#25]
Forgive any mistakes, I'm new to using Github and all the fancy developer language is very confusing. I just updated to Falling Leaves 1.9.0 but my game crashed when trying to start. I've attached the crash log (I think?). Until then, I'll revert back to 1.8.1. :)

[crash-2022-01-13_14.28.48-client.txt](https://github.com/RandomMcSomethin/fallingleaves/files/7865541/crash-2022-01-13_14.28.48-client.txt) 

Thanks so much for the awesome mod!

**Comment by Fourmisain** [comment]
Ahhh, now I understand!

This was really confusing because what the crashlog says should be impossible and I double checked the CurseForge jar with my own and they were 100% identical.

Turns out I uploaded the wrong jar file to Modrinth!
Correct version is now up, sorry about that!

**Comment by SepiaPages** [comment]
OH NEAT haha glad I could help!!
