### ISSUE TITLE
The falling leaves are rendered when you are in a banner

### ISSUE THREAD

**Issue by Lolothepro** [RandomMcSomethin/fallingleaves#26]
The falling leaves are rendered when you are in a banner

![2022-03-12_10 33 39](https://user-images.githubusercontent.com/68275908/158012623-9e2ed348-2876-477a-bf7c-0f35a54d2495.png)

**Comment by Fourmisain** [comment]
That's just vanilla rendering, happens with all particles and clouds and water too (see [MC-167532](https://bugs.mojang.com/browse/MC-167532)):
![vanilla](https://user-images.githubusercontent.com/8464472/158050039-1d4f7249-e353-43a3-8f93-dcdd66acbac6.png)
Same with Sodium.

Pretty sure it's some kind of transparency ordering issue, Minecraft has a lot of these, e.g. particles get cut off by the water surface too.

Either way, it's not a bug in Falling Leaves and we can't fix it either.
