### ISSUE TITLE
1.17.1 broken

### ISSUE THREAD

**Issue by madethisaccounttoreportstuff** [RandomMcSomethin/fallingleaves#35]
i tried to boot up minecraft version 1.17.1 with falling leaves installed, upon booting up minecraft, i was greeted with this.
![image](https://user-images.githubusercontent.com/109210062/178692217-10915a15-1080-4d2f-a124-5ce1e98b1356.png)
please fix it.

**Comment by Fourmisain** [comment]
You need to send us the actual crash report, not just the error screen you know... 😅
As it says on there:

> Click the "Get link" button to open it in your browser. You're encouraged to send this report to the mod's author

That said, this error either because you're using outdated Cloth Config / Fabric API or loader or more likely because of a mod conflict, the 1.17 version by itself isn't "broken".

**Comment by Fourmisain** [comment]
I guess there won't be any reply.
I tested the 1.17 version working and have no idea what this could be a conflict with without the crash report :shrug:
