### ISSUE TITLE
Update Mod Menu Appearence

### ISSUE THREAD

**Issue by MopsTMC** [RandomMcSomethin/fallingleaves#4]
Hello! I just downloaded the new version (1.2) of FallingLeaves and I just want to point out that there is no translation for the decay time of leaves and there is a wrong tip saying that the default value for that is 0.1. Also, it would be nice to add a specification that the leaf decay time is in ticks. Nevertheless, great mod! Really adds to the environment. Keep up the good work and thanks! :)
![2020-11-16_20 54 32](https://user-images.githubusercontent.com/74558936/99297049-614f1700-2850-11eb-9698-4f1c5a401dfb.png)

**Comment by Fourmisain** [comment]
Config descriptions are fixed in version 1.3, thanks for the report!
