### ISSUE TITLE
Not working on 1.19.3

### ISSUE THREAD

**Issue by SpiritOTHawk** [RandomMcSomethin/fallingleaves#41]

**Comment by Fourmisain** [comment]
Yes it is - working, that is.
Are you sure you installed the latest [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all?filter-game-version=2020709689%3A7499) and [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all)?

If so, describe what isn't working.
Is it crashing? If so, crash report please!

**Comment by Fourmisain** [comment]
In the same vein make sure you're actually using the [latest release](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric/files/all) of Falling Leaves.

**Comment by SpiritOTHawk** [comment]
Yeah, I didn't update, sorry)
