### ISSUE TITLE
Cloth Config Dependency Outdated

### ISSUE THREAD

**Issue by juancarloscp52** [RandomMcSomethin/fallingleaves#42]
Hello! The cloth config version that [Falling Leaves is using](https://github.com/RandomMcSomethin/fallingleaves/blob/587a4a127aef066ef96d1e79d736ad9d1fb73152/gradle.properties#L18) is 9.0.93 which does not work with the 1.19.3 release as is compatible only with 1.19.3 pre release 2. Version 9.0.94 works fine for 1.19.3.
This breaks other mods when your mod is installed, as sometimes the cloth config version that your mod includes takes priority.
[See more here](https://github.com/juancarloscp52/BedrockIfy/issues/197)

Hope it helps, thanks!

**Comment by Fourmisain** [comment]
Falling Leaves does not contain Cloth Config. (It once did ages ago in 1.6.0 for Minecraft 1.16.)
What you were seeing is simply the version it was compiled against which does not affect execution in any way.

For the issue you were seeing:
Mods that are contained in other mods (jar-in-jar mods) are [sorted by version and can only be overridden by top-level mods](https://github.com/FabricMC/fabric-loader/blob/8e128c2357550026d8478e724c4cbea10a99d411/src/main/java/net/fabricmc/loader/impl/discovery/ModResolver.java#L210-L214), meaning there is no randomness to this and Goober19 had Cloth Config 9.0.93 installed directly.
