### ISSUE TITLE
Immersive weathering messing with this mod's particles

### ISSUE THREAD

**Issue by slovinsqui** [RandomMcSomethin/fallingleaves#50]
I prefer using falling leaves particles over the immersive weathering ones, but it turns out immersive weathering leaf configurations also affects your mod, this leading to me trying to disable the other´s mod particles, wich also disables the ones from this mod

**Comment by Fourmisain** [comment]
Hm... I can't seem to reproduce this.
I used Immersive Weathering 1.2.9 for 1.19.2, turned off "Falling Leaf Particles" in the client config and Falling Leaves (1.13.0) still works as expected.

Are you by chance looking at an evergreen like a spruce tree?
Or are you using a different mod version?

**Comment by slovinsqui** [comment]
oh yeah, turns out I just had the spawn rate really low so i did not notice the one leaf that spawns lol
sorry for wasting your time pal, hope you have a good day c:
