### ISSUE TITLE
simply isnt spawning leaves, creating wind, etc.

### ISSUE THREAD

**Issue by Mope-a-latte** [RandomMcSomethin/fallingleaves#51]
Im running 1.18.2 fabric version along side a bunch of mods, 
![Capture](https://github.com/RandomMcSomethin/fallingleaves/assets/83788751/0644c479-4a60-4c09-9cdb-c68d9cd0e125)
it simply isnt actually spawning any leaves, making trees move or anything. if you have a discord or something id likely be able to simply show you. do you know if one of these mods conflict with it? (ive tried CULL LEAVES it doesnt change anything when turned off)

**Comment by Mope-a-latte** [comment]
Hey i figured it out, it started working after opening CLOTH API in mod manager for the first time, i dont know if this is because of sodium or what. 

ON ANOTHER NOTE: the IRIS shader pack is being buggy with it, i think im going to have to figure out that and send another comment in!

**Comment by Fourmisain** [comment]
Not sure what happened that leaves weren't spawning; it might not yet have initialized the config yet or something?
You weren't looking at evergreen trees, right?
I'm almost 100% certain none of your mods are incompatible with Falling Leaves (as I used all of them at least once) and if it's fixed now, let's just count it as a one-time blunder.

If your shaders are making the falling leaves look weird (or what do you mean by "being buggy"?), then there's nothing we can do about it.
The shaders decide how to render the game, we just spawn particles.
It might an issue with Iris or an issue with the shaders themselves, so you can try report this to the shader or Iris devs if you're certain there's something wrong.
