### ISSUE TITLE
Use 'fabric-api' mod ID in fabric.mod.json 

### ISSUE THREAD

**Issue by Poopooracoocoo** [RandomMcSomethin/fallingleaves#56]
Users may be confused when they see that it depends on `fabric`, not knowing that it's referring to the Fabric API. 

>As of Minecraft 1.19.2, Fabric API's mod ID has changed from `fabric` to `fabric-api`. When backporting from 1.19.2 to earlier versions, you must alter the `depends` section of your `fabric.mod.json` to expect `fabric`.

From https://fabricmc.net/wiki/tutorial:setup#mod_setup

---

You should also add the Fabric API dependency for releases on CF and MR so that launchers can download it automatically.

**Comment by Fourmisain** [comment]
Changed in 107449b92aa8997aaa5458b7be0826f965a01604, will be in the next version.
CF already had the dependencies set.
I added them to MR (latest, 1.19.2 and 1.18.2 at least), but it looks like I need to do that manually each time I release a new version, so I might forget... Maybe I should finally add a publish script to the build.

**Comment by Poopooracoocoo** [comment]
Thank you!!

I tend to see projects use the [MC-Publish](https://github.com/Kir-Antipov/mc-publish) GitHub Action, if you're not already using that. Not sure if that'd help with anything, but not everyone knows of it.
