### ISSUE TITLE
Hitting & breaking leaves still produces particles irrespective of the spawn rate

### ISSUE THREAD

**Issue by MerpisMe** [RandomMcSomethin/fallingleaves#57]
the title is pretty much the gist of it; setting the spawn rate to 0 still spawns leaves when breaking or hitting leaves

**Comment by Fourmisain** [comment]
That is sorta the idea. The leaves are meant to signify you are breaking the block (ruffling up / cutting up the tree), just like the regular block breaking particles.

**Comment by MerpisMe** [comment]
i guess that's fair, though i'd still prefer if there was an option per block to toggle it

i mainly wanted to see this be fixed since i'm not the biggest fan of cherry leaves still dropping particles; the vanilla ones look far better than the tinted ones in my opinion, and i'd like to at least be able to disable it somehow. that is unless you lot want to make the particles just use the vanilla cherry ones instead, i'd be fine with that too lol

**Comment by Fourmisain** [comment]
Okay, I think this should work...

Yep, I just added a per-block setting for the on-hit leaves, which also applies leaves on decay ("block breaking leaves").

New version is up (on Modrinth, CurseForge takes a second)!

**Comment by MerpisMe** [comment]
oh wow, that was really fast. thank you so much!!

**Comment by Fourmisain** [comment]
Would have been twice as fast if I didn't have to rethink and rename everything after remembering decay leaves are a thing... 😅
